export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export EDITOR=vim

autoload colors
colors

DIRSTACKSIZE=8

source ~/.zsh/os.zsh
source ~/.zsh/alias.zsh
source ~/.zsh/le.zsh
source ~/.zsh/path.zsh
source ~/.zsh/prompt.zsh
source ~/.zsh/up.zsh
source ~/.zsh/darcs.zsh
source ~/.zsh/cmd.zsh
source ~/.zsh/pass.zsh
source ~/.zsh/env.zsh

if darwin; then
  eval $(brew shellenv)
fi

autoload -Uz compinit
compinit
zstyle ':completion:*' menu select=4

if linux || freebsd; then
  source ~/.zsh/x11.zsh
  . $HOME/.zsh/z.sh
  unset SSH_ASKPASS
elif darwin; then
  . `brew --prefix`/etc/profile.d/z.sh
fi

for each in `find ~/.zsh/local -name \*.zsh`; do
  source $each
done

if [ -e $HOME/banner ] && [ -s $HOME/banner ]; then
  echo +++
  cat $HOME/banner
  echo +++
fi

# Fix `z` in WSL
if wsl; then
  setopt nobgnice
fi
